language: python

python:
  - "2.7"

before_install:
  - which "python"
  - python -c "import sys; print sys.path"

addons:
  apt:
    packages:
      - scons
        #- texlive-full
cache:
  directories:
    - $HOME/TeXLive2015

install:
  - python bin/downloads.py
  - if [ -e "$HOME/TeXLive2015/bin/x86_64-linux" ]; then
      echo "$HOME/TeXLive2015/bin/x86_64-linux EXISTS";
    else
      echo "$HOME/TeXLive2015/bin/x86_64-linux DOES NOT EXIST";
    fi
  - python bin/install-tex.py --repository="http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet"
  - PATH="$HOME/TeXLive2015/bin/x86_64-linux:$PATH"

before_script:
  - echo $PATH
  - scons --version

script:
  - scons
